### ISSUE TITLE
[RFE] Allow the usage of Gradle build files for the Source + Dependencies Analysis mode

### ISSUE THREAD

**Issue by rromannissen** [konveyor/enhancements#104]
The source+dependencies analysis mode doesn't recognize Gradle build files, so it's not able to retrieve the required dependencies. Even though the usage of Gradle is not as widespread as Maven's, it would be good to cover this use case as well. A way to approach it could be to transform the Gradle build file into a POM, and use the logic we already have from there. The [Maven Publish Plugin from Gradle](https://docs.gradle.org/current/userguide/publishing_maven.html) seems to be able to do this as explained [here](https://www.baeldung.com/gradle-build-to-maven-pom).

**Comment by rromannissen** [comment]
@pranavgaikwad @jmle is this something that the new analyzer allows? I imagine the Java Language Server is compatible with Gradle build files, is there a way to test this?

**Comment by jmle** [comment]
@rromannissen [according to the feature list](https://github.com/eclipse-jdtls/eclipse.jdt.ls#features) the JDT LS supports Gradle projects, but we would need to implement support for dependency search and so on in case the project uses gradle.

**Comment by rromannissen** [comment]
@dymurray this needs to be prioritized for 0.4.0.

**Comment by mail2nadeem92** [comment]
Hello @rromannissen,

Please add a size label (size/XS, size/S, size/M, size/L, size/XL) to assist in the Konveyor planning process.

**Comment by jmle** [comment]
This has actually been documented as an enhancement in https://github.com/konveyor/enhancements/tree/master/enhancements/gradle-support and implemented in https://github.com/konveyor/analyzer-lsp/pull/609. I will close the RFE.
