### ISSUE TITLE
[RFE] Improve Assessment capabilities to support intelligent workflows and customizations

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/enhancements#114]
This RFE is tracking work to expand the assessment capabilities in Konveyor to support at a minimum:

- Customizations - allow end users to customization assessment questions/answers as they choose
- Intelligence - provide a richer form of controlling workflows inside of an assessment so future questions may be presented based on info from an analysis and/or answers to prior questions

This RFE is not complete, we will come back to update and refine as the fuller scope of needs are identified.

**Comment by jwmatthews** [comment]
Related to https://github.com/konveyor/tackle-pathfinder/issues/152

See [slack conversation in #konveyor ](https://kubernetes.slack.com/archives/CR85S82A2/p1679408492361779) on March 21-22, 2023

**Comment by rromannissen** [comment]
Solved by #120
