### ISSUE TITLE
[RFE] Dynamic Reports - Incident: Add line numbers to the `codeSnip` string (right-aligned)

### ISSUE THREAD

**Issue by mturley** [konveyor/enhancements#124]
When rendering the `codeSnip` string of an Incident in the UI, we display line numbers from the source file in a gutter to the side of the code snippet. In order to align these numbers correctly and correctly mark the actual offending line, we need to know how much context is provided in the code snippet around the actual line numbered by the Incident's `line` property. I propose a `codeSnipStartLine` or similarly-named property, which would be the line number where the codeSnip begins.

**Comment by mturley** [comment]
cc @shawn-hurley @jortel @pranavgaikwad

**Comment by mturley** [comment]
Note that @shawn-hurley mentioned earlier that the codeSnip should start 10 lines above, but that doesn't cover the case where a file is fewer than 10 lines in total. Also, the UI should not hard-code the number of context lines here so that we can decide to have the analyzer provide more/less context in the future without a UI change.

**Comment by mturley** [comment]
(I just realized I could still strip left-aligned numbers out by using the length of the last line number for all lines, but I still have a preference for right-aligned numbers as that's what editors tend to use and it looks nicer)

**Comment by shawn-hurley** [comment]
I am no opposed to this, and it does make sense we will do the same logic, but if the context number is configurable, it makes sense for that logic to live there. Note to anyone implementing this on the analyzer-lsp I am pretty sure most of our stuff is 0 indexed not 1.

**Comment by shawn-hurley** [comment]
@pranavgaikwad I think we can move this to the analyzer then (as it seems all the work is on our side now) and I believe that we should align to Demo E. What are you thoughts?

**Comment by mturley** [comment]
> I am pretty sure most of our stuff is 0 indexed not 1.
@shawn-hurley do you mean the `line` property on an Incident is 0-indexed, and I should be showing `line + 1` in the UI?

**Comment by shawn-hurley** [comment]
What our providers return is 0 indexed, I assume that you would want that to be 1 indexed. just means we have to add by one

**Comment by pranavgaikwad** [comment]
Created issue to track, adding it on Demo E

**Comment by mturley** [comment]
Note for implementation (cc @pranavgaikwad): @jortel and I agreed that the code snip lines should have exactly 2 additional spaces between the line number and the code (not including any leading whitespace from the source code itself). See https://github.com/konveyor/tackle2-hub/pull/414 for an example.

**Comment by rromannissen** [comment]
@mturley can we consider this done already? I see that the related PR has been merged.

**Comment by mturley** [comment]
Ah yes, this is done. Thanks @rromannissen
