### ISSUE TITLE
[RFE] Dynamic Reports - Incident: Add some indication of the source code language

### ISSUE THREAD

**Issue by mturley** [konveyor/enhancements#125]
When rendering the `codeSnip` of an Incident in the UI, we would like to use syntax highlighting where possible. If the language is known and we can provide a `language` property on the Incident (or somewhere on the `Issue` or `File` or wherever it makes sense), the UI can have some supported list of languages it knows how to highlight. If the language is missing or unrecognized the UI can fall back to no syntax highlighting.

As part of this we should also determine the list of supported languages for which we need syntax highlighting.

**Comment by mturley** [comment]
cc @shawn-hurley @jortel @pranavgaikwad

**Comment by mturley** [comment]
@pranavgaikwad do you think the detection based on filename extension is sufficient and we should close this?

**Comment by shawn-hurley** [comment]
For now, the filename extension should be sufficient. I don't think that we should try to do anything else that is too fancy IMO

**Comment by mturley** [comment]
Works for me.
