### ISSUE TITLE
[UI] Tag spacing

### ISSUE THREAD

**Issue by JustinXHale** [konveyor/enhancements#148]
**Problem/Solution**

The spacing after a tag icon should be increased to provide space between the label and text.
PF Example https://www.patternfly.org/extensions/component-groups/tag-count/#basic-tag-count

**Questions**
- Is the tag icon needed with tag in the header?
- Does the icon add to the experience for the user?

![image](https://github.com/konveyor/enhancements/assets/91554933/15080535-ea5c-4ffb-a17e-6a8cdfecea2d)

**Comment by sjd78** [comment]
Implemented with konveyor/tackle2-ui#1878
