### ISSUE TITLE
[RFE] Add support for analysis of .NET applications

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/enhancements#154]
This is to track enhancement around .NET language provider.

**Comment by djzager** [comment]
Original enhancement #128 . I think with what we know now about new .NET versus old .NET, we will need to just start a new one.

**Comment by djzager** [comment]
Keep this issue in mind https://github.com/konveyor/rulesets/issues/4

**Comment by djzager** [comment]
Documented in #167
Implemented in konveyor/analyzer-lsp#539

What has been documented and implemented is simply the dotnet-external-provider that can be run to perform rules based analysis of .NET applications. This is not yet fully baked into the Konveyor UX.

**Comment by mail2nadeem92** [comment]
Hello @pranavgaikwad,

Please add a size label (size/XS, size/S, size/M, size/L, size/XL) to assist in the Konveyor planning process.
