### ISSUE TITLE
Java provider get maven artifact for binary analysis. 

### ISSUE THREAD

**Issue by jortel** [konveyor/enhancements#161]
Java provider get maven artifact using coordinates for binary analysis instead of the addon.

**Comment by pranavgaikwad** [comment]
Being addressed here https://github.com/konveyor/analyzer-lsp/issues/554

**Comment by dymurray** [comment]
Keeping this on 0.5.0 for now, if cannot address by 7/23 we will kick to 0.5.1

**Comment by jortel** [comment]
Included in 0.5.1.
