### ISSUE TITLE
[RFE] Automatic language and technology discovery for applications

### ISSUE THREAD

**Issue by rromannissen** [konveyor/enhancements#170]
### What is the problem?

Getting insights about the language and technology stack of an application requires the user to run an analysis on it.

### Why is this a problem?

On large portfolios, having to manually schedule an analysis on all applications to start figuring out their language and technology stack could be cumbersome and somehow counterintuitive. The natural flow would be to first understand the language and technology stack of an application, and based on that, potentially have it aligned with an existing archetype to then run the analysis for the most suitable migration target based on that information. 

### Proposed solution

Automate the process of discovering first the language and then the technology stack for applications in the portfolio. When idle, the hub should automatically create language/technology stack discovery tasks for applications that don't have that information available yet in the portfolio. Certain considerations should be taken into account:

- Language/technology stack discovery should be triggered by certain events: application creation, application import, repository modification, credentials association... For example, if language/technology stack discovery failed on an application because the associated credentials are wrong, the system shouldn't try again until new credentials are provided. 
- Automatic discovery should happen with "spare cycles" available in the resources pool. Users shouldn't have to wait until an automatic discovery task is finished to run things like analysis. User requested tasks should always have preference over tasks executing in the background.
- Language/technology stack discovery should be implicit for application analysis. If for whatever reason one application doesn't have its language/technology stack information available yet, when trying to run an analysis on it, those operations will be executed before the actual analysis is executed.

**Comment by jortel** [comment]
Recommend these fields for tasks to begin with:
- ID
- Kind
- State
- Priority
- Application

**Comment by sjd78** [comment]
Related UI work:
  - https://github.com/konveyor/tackle2-ui/issues/1934
