### ISSUE TITLE
[RFE] Surface the Task Manager in the UI

### ISSUE THREAD

**Issue by rromannissen** [konveyor/enhancements#171]
### What is the problem?

There's no way for the user to understand which tasks are being executed and the queue of pending tasks. 

### Why is this a problem?

By not knowing what is being executed and scheduled at a given moment, users might feel like the system is unresponsive, especially in multi-user environments. 

### Proposed solution

Surface information about what is queued for execution by the task manager. This view should provide a way for users to:

- Browse the task queue. For each task the following information should be provided:
   - Task ID.
   - Task type: Analysis, discovery...
   - User that created the task.
   - Status: Scheduled, In progress...
- Cancel background tasks like automatic language/technology stack discovery (see #170 for more information about this). Cancelled background tasks will be rescheduled again automatically at the end of the queue.
- Cancel the tasks created by the current user. Tasks created by other users can't be cancelled.

**Comment by rromannissen** [comment]
@jortel @mansam @JustinXHale for your consideration.

**Comment by sjd78** [comment]
Related UI work:
  - https://github.com/konveyor/tackle2-ui/issues/1931
  - https://github.com/konveyor/tackle2-ui/issues/1934

**Comment by jortel** [comment]
Hub work:

- https://github.com/konveyor/tackle2-hub/pull/640
