### ISSUE TITLE
[RFE] Enhancing Information Rules/ Tags with Additional Details

### ISSUE THREAD

**Issue by kthatipally** [konveyor/enhancements#175]
Currently, static-reports generated by Kantra utilizes tags to provide basic information utilizing our information rules. While these tags offer some insight, they often fall short in conveying comprehensive details about input applications. We are requesting to enhance the existing tagged rules by providing additional details beyond tags to provide deeper understanding of the input applications. These supplementary fields would offer users more comprehensive insights, to empower users with greater clarity in discovering the input applications. This is particularly useful when running the analysis on the old legacy applications.

**Comment by shawn-hurley** [comment]
Hello,

We hank you for the request, I do wonder if the insights enhancement https://github.com/konveyor/enhancements/pull/174 covers the use case. 

Can you give that a review and see if we are missing something in that enhancement?

**Comment by dymurray** [comment]
https://github.com/konveyor/static-report/pull/114
