### ISSUE TITLE
[RFE] Allow the association of target platforms with Archetypes

### ISSUE THREAD

**Issue by rromannissen** [konveyor/enhancements#186]
### What is the problem?

There is no way for an organization to enforce certain migration paths for applications associated with a certain archetype to land on specific target platforms. This allows migrators to explore migration paths that are not sanctioned by the organization, opening up the door for runtime/platforms and technology stacks that don't meet the corporate policy.

### Why is this a problem?

After interviewing several large organizations, it has been revealed that modernization projects are perceived by them as an opportunity to further standardize the application landscape, narrowing down the number of allowed archetypes, technology stacks and runtime/platforms to a few supported options. For MTA to be useful on that approach at scale, there needs to be a way for organizations to model the supported runtimes/platforms and technology stacks and associate them with archetypes, and from there, streamline and simplify the analysis process for migrators.

### Proposed solution

- The concept of _Target Platform_ will be introduced to model a potential runtime/platform for applications that are associated to a given archetype. 
- For each _Target Platform_ associated to a given archetype, users should be able to associate one or many migration paths.
    - _Target Platforms_ could have different sets of migration paths for different archetypes. For example, the "Kubernetes" _Target Platform_ could include the _OpenJDK 21_, _EAP 8_ and _Containerization_ migration paths for the "EAP 6" archetype, and then include the _OpenJDK 21_ and _Containerization_ migration targets for the "Spring Boot" archetype.

![Screenshot from 2024-07-08 15-52-08](https://github.com/konveyor/enhancements/assets/15966456/c0d8fe5b-c66f-40c0-bc6d-959360c4ce51)

- These relationships could be used to enforce certain migration motions for migrators on the analysis wizard or external systems like the CLI, IDE plugins and potential future integrations with Backstage.

### Open Questions

- Should this relationship be managed in the _Migration_ or the _Administration_ perspective?

**Comment by sjd78** [comment]
Some of my initial thoughts:

  - Migration Paths seem like another way to describe a migration target, which really is a ruleset target label. For example, the "Application server migration to" target card with "JBoss EAP 8" selected ultimately enables the label `konveyor.io/target=eap8` on an analysis.

  - Target Platform looks like a collection of target labels.  Following the example in the diagram, Kubernetes could be a set of labels ` konveyor.io/target=cloud-readiness`, `konveyor.io/target=openjdk21`, and `konveyor.io/target=eap8`.

  - Archetypes would just need to be extended to support a collection of Target Platforms.

  - If an Archetype has a set of Target Platforms, the Analysis Wizard would just union the set of Target Platforms from all selected Applications, and then either...
    - Preselect the target cards based on the union of target platform labels, or
    - Allow selection of targets by selecting the target platforms (2 sets of selections would be available -- Target Platforms and Target Cards)
    - Question: If Target Platforms are in effect via an Application's Archetype, can the target cards still be selected directly?

**Comment by rromannissen** [comment]
@sjd78 I think you are totally right in your assumptions. About your question, I think that could be a configuration thing, allowing the admin to restrict whether migrators can still make choices outside the indirect relationship between archetypes and migration paths or not. Example: If an application belongs to Archetype EAP 6 associated with Kubernetes and Traditional Standalone, allowing migrators to still manually select "Quarkus" or not would depend on some configuration parameter.

**Comment by rromannissen** [comment]
An enhancement has been successfully submitted, but the feature hasn't been implemented. Reopening the issue.
