### ISSUE TITLE
[RFE] Allow architects to review an application without an assessment

### ISSUE THREAD

**Issue by rromannissen** [konveyor/enhancements#88]
Overall feedback for the Assessment module in Konveyor is that it is too opinionated and is not flexible enough to adapt to the landscape of all organizations. Given that fact, some user have their own approach to assessment using their own questionnaires and sessions, but would like to be able to reflect their decisions in terms of the most suitable migration strategy for each application without having to fill in the builtin assessment questionnaire.

Right now Tackle forces users to fill the assessment questionnaire in order to be able to review an application. The request would be that, as an architect, users should be able to review applications and determine their strategy, effort and criticality without having to run an assessment first.

**Comment by rromannissen** [comment]
One suggested approach would be to make this configurable, so administrators can determine whether an assessment should be required for the review or not.

**Comment by shawn-hurley** [comment]
I wonder if we can take this a step further, and detach specific surface information from being tied to the review, rather the review is just shown all the information that has surfaced for the application regardless of source. 

I guess the question that I am asking is, is this a short-term ask for the next release or do we have the time to rethink this entire interaction between various surfacing information tools and the hub and the UI and the hub for the release after that?

**Comment by rromannissen** [comment]
I think enabling this is a low hanging fruit that would bring value to the field quickly. Since we have the intention of rethinking the entire assessment module in the mid to long term, we have plenty of time rearrange the relationships between different entities and their corresponding surfaced information.

**Comment by mail2nadeem92** [comment]
Hello @rromannissen,

Please add a size label (size/XS, size/S, size/M, size/L, size/XL) to assist in the Konveyor planning process.
